<?php
$z[0]=Array("field","",271,290);
$z[0][4]['name']="title";
$z[1]=Array("global","",291,317);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",358,387);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",427,485);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",781,816);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1100,1121);
$z[5][4]['name']="content";
$z[6]=Array("include","",1221,1258);
$z[6][4]['filename']="footer.htm";

?>