<li> <a href="[field:arcurl/]" class="red-jia"><img src="/skin/images/red_jia.png"  /></a> <a href="[field:arcurl/]" class="product-thumbnail"><img src="[field:picname/]" width="198px" height="245px" /> <span class="focus-product-bt">·&nbsp;&nbsp;[field:title/]</span> <span class="focus-product-content">
        <h2>[field:title/]</h2>
        <p>[field:description function='cn_substr(@me,60)'/]...</p>
        </span></a> </li>