<?php
$z[0]=Array("channel","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n        <li class=\"line\">|</li>\r\n        ",275,434);
$z[0][4]['type']="top";
$z[0][4]['row']="10";
$z[1]=Array("global","",483,505);
$z[1][4]['name']="cfg_tel";
$z[2]=Array("global","",521,546);
$z[2][4]['name']="cfg_adress";
$z[3]=Array("global","",564,590);
$z[3][4]['name']="cfg_powerby";
$z[4]=Array("global","",591,615);
$z[4][4]['name']="cfg_beian";
$z[5]=Array("global","",808,830);
$z[5][4]['name']="cfg_tel";

?>